### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by nickostyle** [schwa23/cleanupsfui#10]
I like the idea, but can not understand how it works. What should I choose on iMac 27? Retina or non-retina? If I choose non-retina the fonts become bigger every time I fix them with this plugin. What is wrong?

**Comment by schwa23** [comment]
The preference for designing at 1x or 2x depends on if you design in Points or Pixels.

For instance, an iPhone 7 is 350x667 pts (1x), but 750x1334 px (2x). If you design where 2px = 1pt, then choose 1x. If you design where 1px = 1px, choose 2x.

**Comment by allisonacs** [comment]
Fwiw, I believe the bug he reported is real: I design at 1x, and when I
used the updated plugin, it made the text extremely large. My plugin was
configured correctly for the resolution I design at.
