### ISSUE TITLE
Plugin does not respect @1x setting

### ISSUE THREAD

**Issue by allisonacs** [schwa23/cleanupsfui#11]
I design @1x. I have set my plugin to use the @1x setting. However, when I run the plugin, it changes my type size to be @2x (e.g. 14px > 28px). 

[See replication procedure in this GIF](https://gfycat.com/gifs/detail/TightEvergreenBobolink)

This references https://github.com/schwa23/cleanupsfui/issues/10

**Comment by viowai** [comment]
Me, too. 
I'm using Sketch 47. @schwa23

**Comment by schwa23** [comment]
Thanks for the GIf. I will look into it.
