### ISSUE TITLE
1.5.2 breaks plugin

### ISSUE THREAD

**Issue by allisonacs** [schwa23/cleanupsfui#12]
Sorry to keep filing bugs. 

After installing the latest update via Sketch's update system, the plugin disappears from the plugin menu, although the plugin file remains in the plugins folder. 

After manually deleting the plugin and reinstalling it, the problem persists (not present in the plugin menu, but present in the plugin folder). 

![image](https://user-images.githubusercontent.com/1230973/31520535-fa3006f4-af5a-11e7-9f8d-32d8c69cb45d.png)

**Comment by schwa23** [comment]
Are you running v47?

**Comment by allisonacs** [comment]
46.2 (have to hold off on the update for another day or so). FWIW, this was an issue in the previous release as well, but I was able to resolve it by manually deleting and reinstalling.

**Comment by schwa23** [comment]
I can't reproduce on my end -- I uninstalled and reinstalled and it shows up. I'm not an expert on plugins tho, i'll dig around and see if I can figure it out.  If you have anything in your Console that might be helpful. It's also possible that somehow it's conflicting with another plugin (seems unlikely)? just out of curiousity if you remove all the other plugins except CleanUp SFUI does it appear?

**Comment by schwa23** [comment]
actually I think I have an idea what's going on. the zip file  wasn't packaged properly

**Comment by allisonacs** [comment]
Yea I think you're right. When I downloaded the master and installed from there, it installed properly.

**Comment by schwa23** [comment]
sorry!

**Comment by allisonacs** [comment]
No worries! Thank you for making this plugin and being so responsive to issues! 🙌

**Comment by schwa23** [comment]
Updated the archive in the 1.5.2 release, plus version bumped to 1.5.3 to be safe https://github.com/schwa23/cleanupsfui/commit/eabb98021e27c1719089d82b306840e3e84a4efc
