### ISSUE TITLE
macOS 10.15 Catalina (false alarm)

### ISSUE THREAD

**Issue by jmasci** [schwa23/cleanupsfui#14]
Thank you for this plug-in, it has been super helpful for me.

I just updated my Mac to Catalina and the plug-in appears to have stopped working. The clean up action has no effect.

However, my Sketch license has also recently expired, so possibly I am missing a Sketch update that would resolve the problem?

**Comment by jmasci** [comment]
Just realized the plug-in is still working in other files, so there is something broken in the file I'm currently working on. At this point I have no idea what caused it to stop working.

**Comment by schwa23** [comment]
Glad it’s an isolated issue (sorry it’s not working on that file). I haven’t updated to Catalina yet so hopefully it’s unrelated.

**Comment by jmasci** [comment]
I've been dropping emojis into that file and it appears to be related to that, however, I can't figure out reliable steps because I've tried testing with emojis in other files and sometimes the plugin works, other times it doesn't.
