### ISSUE TITLE
texts with multiple weight are not respected

### ISSUE THREAD

**Issue by ralts00** [schwa23/cleanupsfui#6]
help, when I have text with multiple weights, the plugin homologates everything and the weight styles are lost.
Thanks.
your work is wonderful!!!!

![multi](https://user-images.githubusercontent.com/5034252/30298268-67963640-9710-11e7-9611-6422db41395f.gif)

**Comment by schwa23** [comment]
Added support! https://github.com/schwa23/cleanupsfui/commit/9be6cc8d469d594c869c998ebc4172047f23e6d7
